cmake_minimum_required(VERSION 3.28)
project(aot_sdk_smoke LANGUAGES C CXX)
find_package(LLVM 18.1.3 EXACT REQUIRED CONFIG)
find_package(MLIR REQUIRED CONFIG)
find_package(LibArchive REQUIRED)
add_executable(sdk-mlir-smoke mlir.cpp)
target_compile_features(sdk-mlir-smoke PRIVATE cxx_std_17)
target_include_directories(sdk-mlir-smoke SYSTEM PRIVATE ${LLVM_INCLUDE_DIRS} ${MLIR_INCLUDE_DIRS})
target_link_libraries(sdk-mlir-smoke PRIVATE MLIRIR MLIRSupport LLVM LibArchive::LibArchive)
