// Generated by sdk/targets.py cpp; edit sdk/targets.json.
#include "sela/Targets.h"

namespace sela::targets {
namespace {
const TargetInfo registry[] = {
  {"x86_64", "x86_64-unknown-linux-gnu", "x86_64-linux-gnu", "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128", "x86_64-linux-gnu", "x86_64-linux-gnu", "X86", "sysv-amd64", "x86-64", "+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87", "default", "little", "ld-linux-x86-64.so.2", "x86_64", "elf_x86_64", "amd64", "qemu-x86_64", 64, 2, 62, true},
  {"i686", "i686-unknown-linux-gnu", "i686-linux-gnu", "e-m:e-p:32:32-p270:32:32-p271:32:32-p272:64:64-i128:128-f64:32:64-f80:32-n8:16:32-S128", "i386-linux-gnu", "i686-linux-gnu", "X86", "sysv-i386", "i686", "+cmov,+cx8,+x87", "default", "little", "ld-linux.so.2", "i386", "elf_i386", "i386", "qemu-i386", 32, 1, 3, true},
  {"armv7", "armv7-unknown-linux-gnueabihf", "armv7-linux-gnueabihf", "e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64", "arm-linux-gnueabihf", "arm-linux-gnueabihf", "ARM", "aapcs32-vfp", "generic", "+armv7-a,+dsp,+fp64,+vfp2,+vfp2sp,+vfp3d16,+vfp3d16sp,-aes,-d32,-fp-armv8,-fp-armv8d16,-fp-armv8d16sp,-fp-armv8sp,-fp16,-fp16fml,-fullfp16,-neon,-sha2,-thumb-mode,-vfp3,-vfp3sp,-vfp4,-vfp4d16,-vfp4d16sp,-vfp4sp", "hard", "little", "ld-linux-armhf.so.3", "armhf", "armelf_linux_eabi", "armhf", "qemu-arm", 32, 1, 40, false},
  {"aarch64", "aarch64-unknown-linux-gnu", "aarch64-linux-gnu", "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128", "aarch64-linux-gnu", "aarch64-linux-gnu", "AArch64", "aapcs64", "generic", "+fp-armv8,+neon,+v8a,-fmv,-outline-atomics", "default", "little", "ld-linux-aarch64.so.1", "aarch64", "aarch64linux", "arm64", "qemu-aarch64", 64, 2, 183, false},
};
const llvm::StringRef flags_armv7[] = {"-march=armv7-a", "-mfpu=vfpv3-d16", "-mfloat-abi=hard"};
const llvm::StringRef flags_aarch64[] = {"-march=armv8-a"};
const llvm::StringRef publication_flags_aarch64[] = {"-mno-outline-atomics", "-mno-fmv"};
} // namespace

llvm::ArrayRef<TargetInfo> all() { return registry; }
const TargetInfo *find(llvm::StringRef id) {
  for (const auto &target : registry) if (target.id == id) return &target;
  return nullptr;
}
llvm::ArrayRef<llvm::StringRef> clangArgs(const TargetInfo &target) {
  if (target.id == "armv7") return flags_armv7;
  if (target.id == "aarch64") return flags_aarch64;
  return {};
}
llvm::ArrayRef<llvm::StringRef> publicationArgs(const TargetInfo &target) {
  if (target.id == "aarch64") return publication_flags_aarch64;
  return {};
}
} // namespace sela::targets
