#include "NativeTargets.h"
#include "sela/IR/Compiler.h"

// This per-library list is generated by CMake from registered targets. A
// consumer library references exactly one backend; public metadata is shared.
namespace sela::detail {
#define SELA_NATIVE_BACKEND(ID) namespace native_##ID { const NativeTargetBackend &backend(); }
#include "sela/LinkedNativeTargets.inc"
#undef SELA_NATIVE_BACKEND
}

namespace sela {
llvm::ArrayRef<llvm::StringRef> supportedNativeTargets() {
  static const llvm::StringRef targets[] = {
#define SELA_NATIVE_BACKEND(ID) #ID,
#include "sela/LinkedNativeTargets.inc"
#undef SELA_NATIVE_BACKEND
  };
  return targets;
}

const detail::NativeTargetBackend *detail::findNativeTarget(llvm::StringRef id) {
#define SELA_NATIVE_BACKEND(ID) if (id == #ID) return &native_##ID::backend();
#include "sela/LinkedNativeTargets.inc"
#undef SELA_NATIVE_BACKEND
  return nullptr;
}

llvm::Expected<std::unique_ptr<llvm::Module>> detail::lowerModule(
    mlir::ModuleOp source, llvm::LLVMContext &context, llvm::StringRef targetID,
    NativeABIInverseHints *inverseHints) {
  auto *target = findNativeTarget(targetID);
  if (!target)
    return llvm::createStringError(llvm::inconvertibleErrorCode(),
        "requested native target is unavailable in this Sela library");
  if (auto error = verifyModuleStructure(source)) return std::move(error);
  return target->lower(source, context, inverseHints);
}
} // namespace sela
