#!/usr/bin/env python3
"""One pre-alpha target registry for shell, CMake, Python and generated C++."""
import argparse
import json
from pathlib import Path
import platform
import re
import shlex
import sys

REGISTRY = Path(__file__).with_name("targets.json")
STRING_FIELDS = ("id", "triple", "sysrootTriple", "layout", "multiarch", "gccTriple",
                 "llvmBackend", "abi", "cpu", "features", "floatABI", "byteOrder",
                 "loader", "compilerRTArch", "lldEmulation", "packageArch", "qemuUser")


def load():
    document = json.loads(REGISTRY.read_text())
    if document.get("format") != "sela-targets-prealpha-1":
        raise ValueError("Unsupported target registry format")
    result = {}
    for target in document["targets"]:
        name = target["id"]
        if not re.fullmatch(r"[a-z0-9_]+", name) or name in result:
            raise ValueError("Invalid or duplicate target ID")
        if target["wordBits"] not in (32, 64) or target["elfClass"] != target["wordBits"] // 32:
            raise ValueError("Inconsistent target word size/ELF class")
        if target["byteOrder"] not in ("little", "big"):
            raise ValueError("Invalid target byte order")
        if any(not isinstance(target[field], str) for field in STRING_FIELDS):
            raise ValueError("Invalid target string field")
        if not all(isinstance(flag, str) and flag.startswith("-")
                   for field in ("clangArgs", "publicationClangArgs") for flag in target[field]):
            raise ValueError("Invalid target Clang arguments")
        result[name] = target
    return result


def get(name):
    try:
        return load()[name]
    except KeyError:
        raise ValueError("Unsupported target: " + name) from None


def host_id():
    machine = platform.machine().lower()
    aliases = {"amd64": "x86_64", "arm64": "aarch64", "armv7l": "armv7", "i386": "i686", "i486": "i686", "i586": "i686"}
    name = aliases.get(machine, machine)
    get(name)
    return name


def variable(field):
    field = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", field)
    return "SELA_TARGET_" + re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", field).upper()


def cpp():
    lines = ['// Generated by sdk/targets.py cpp; edit sdk/targets.json.',
             '#include "sela/Targets.h"', '', 'namespace sela::targets {', 'namespace {',
             'const TargetInfo registry[] = {']
    for target in load().values():
        values = [json.dumps(target[field]) for field in STRING_FIELDS]
        values += [str(target[field]) for field in ("wordBits", "elfClass", "elfMachine")]
        values += ["true" if target["plainCharSigned"] else "false"]
        lines.append('  {' + ', '.join(values) + '},')
    lines += ['};']
    for target in load().values():
        if target["clangArgs"]:
            lines.append('const llvm::StringRef flags_' + target["id"] + '[] = {' +
                         ', '.join(json.dumps(value) for value in target["clangArgs"]) + '};')
        if target["publicationClangArgs"]:
            lines.append('const llvm::StringRef publication_flags_' + target["id"] + '[] = {' +
                         ', '.join(json.dumps(value) for value in target["publicationClangArgs"]) + '};')
    lines += ['} // namespace', '', 'llvm::ArrayRef<TargetInfo> all() { return registry; }',
              'const TargetInfo *find(llvm::StringRef id) {',
              '  for (const auto &target : registry) if (target.id == id) return &target;',
              '  return nullptr;', '}',
              'llvm::ArrayRef<llvm::StringRef> clangArgs(const TargetInfo &target) {']
    for target in load().values():
        if target["clangArgs"]:
            lines.append('  if (target.id == ' + json.dumps(target["id"]) + ') return flags_' + target["id"] + ';')
    lines += ['  return {};', '}', 'llvm::ArrayRef<llvm::StringRef> publicationArgs(const TargetInfo &target) {']
    for target in load().values():
        if target["publicationClangArgs"]:
            lines.append('  if (target.id == ' + json.dumps(target["id"]) + ') return publication_flags_' + target["id"] + ';')
    lines += ['  return {};', '}', '} // namespace sela::targets', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("list", "host", "get", "shell", "cmake", "cpp", "check-cpp", "check-elf"))
    parser.add_argument("arguments", nargs="*")
    args = parser.parse_args()
    if args.command == "list":
        print('\n'.join(load()))
    elif args.command == "host":
        print(host_id())
    elif args.command == "cpp":
        print(cpp(), end="")
    elif args.command == "check-cpp":
        if Path(args.arguments[0]).read_text() != cpp():
            raise ValueError("Generated C++ target registry is stale")
    else:
        target = get(args.arguments[0])
        if args.command == "get":
            value = target[args.arguments[1]]
            print('\n'.join(value) if isinstance(value, list) else value)
        elif args.command in ("shell", "cmake"):
            for field, value in target.items():
                key = variable(field)
                if args.command == "shell":
                    if isinstance(value, list):
                        print(key + "=(" + ' '.join(shlex.quote(item) for item in value) + ")")
                    else:
                        print(key + "=" + shlex.quote(str(value)))
                else:
                    value = ';'.join(value) if isinstance(value, list) else str(value)
                    if any(character in value for character in ('"', '\\', '\n', '$')):
                        raise ValueError("Unrepresentable CMake registry value")
                    print(f'set({key} "{value}")')
        elif args.command == "check-elf":
            for filename in args.arguments[1:]:
                with Path(filename).open('rb') as stream:
                    header = stream.read(52)
                order = target["byteOrder"]
                if (len(header) < 52 or header[:4] != b'\x7fELF' or
                    header[4] != target["elfClass"] or header[5] != (1 if order == 'little' else 2) or
                    int.from_bytes(header[18:20], order) != target["elfMachine"]):
                    raise ValueError("Wrong target ELF ABI: " + filename)
                if target["abi"] == "aapcs32-vfp":
                    kind = int.from_bytes(header[16:18], order)
                    flags = int.from_bytes(header[36:40], order)
                    # ARM EABI5 and the hard-float procedure-call ABI are
                    # separate from ELF32/e_machine. Relocatable objects can
                    # omit the float-ABI bits; linked executables/DSOs cannot.
                    float_abi = flags & 0x600
                    if (flags & 0xff000000 != 0x05000000 or flags & 0x00800000 or
                        (kind in (2, 3) and float_abi != 0x400) or
                        (kind == 1 and float_abi not in (0, 0x400))):
                        raise ValueError("Wrong ARM EABI5 hard-float flags: " + filename)


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, KeyError, IndexError) as error:
        print("target registry: " + str(error), file=sys.stderr)
        sys.exit(1)
