include_guard(GLOBAL)
get_filename_component(_sela_registry_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(READ "${_sela_registry_root}/sdk/targets.json" SELA_TARGET_REGISTRY)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_sela_registry_root}/sdk/targets.json")
string(JSON _sela_target_count LENGTH "${SELA_TARGET_REGISTRY}" targets)
math(EXPR _sela_target_last "${_sela_target_count} - 1")
set(SELA_TARGET_IDS)
foreach(_sela_index RANGE ${_sela_target_last})
  string(JSON _sela_id GET "${SELA_TARGET_REGISTRY}" targets ${_sela_index} id)
  if(NOT _sela_id MATCHES "^[a-z0-9_]+$" OR _sela_id IN_LIST SELA_TARGET_IDS)
    message(FATAL_ERROR "Invalid or duplicate registered Sela target: ${_sela_id}")
  endif()
  list(APPEND SELA_TARGET_IDS "${_sela_id}")
  set(SELA_TARGET_INDEX_${_sela_id} "${_sela_index}")
endforeach()

function(sela_target_property output target property)
  if(NOT target IN_LIST SELA_TARGET_IDS)
    message(FATAL_ERROR "Unknown Sela target: ${target}")
  endif()
  string(JSON value GET "${SELA_TARGET_REGISTRY}" targets ${SELA_TARGET_INDEX_${target}} ${property})
  set(${output} "${value}" PARENT_SCOPE)
endfunction()

find_program(SELA_PYTHON_EXECUTABLE NAMES python3 REQUIRED)
execute_process(COMMAND "${SELA_PYTHON_EXECUTABLE}" "${_sela_registry_root}/sdk/targets.py" host
  OUTPUT_VARIABLE SELA_BUILD_HOST_TARGET OUTPUT_STRIP_TRAILING_WHITESPACE
  RESULT_VARIABLE _sela_host_status)
if(NOT _sela_host_status EQUAL 0)
  message(FATAL_ERROR "No registered build-host architecture; provide matching host SDK support first")
endif()
