# Cross-build either native device ABI with the unmodified publisher Clang.
get_filename_component(_sela_repository "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(SELA_BUILD_SDK_ROOT "${_sela_repository}/.sdk" CACHE PATH "Pinned build-host SDK")
if(NOT SELA_SDK_ROOT OR NOT SELA_DEVICE_TARGET MATCHES "^(x86_64|i686)$")
  message(FATAL_ERROR "Set SELA_SDK_ROOT and SELA_DEVICE_TARGET=x86_64|i686")
endif()
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR "${SELA_DEVICE_TARGET}")
set(_sela_triple "${SELA_DEVICE_TARGET}-linux-gnu")
if(SELA_DEVICE_TARGET STREQUAL "i686")
  set(_sela_multiarch i386-linux-gnu)
else()
  set(_sela_multiarch x86_64-linux-gnu)
endif()
set(CMAKE_SYSROOT "${SELA_SDK_ROOT}/sysroots/${_sela_triple}")
set(_sela_host_llvm "${SELA_BUILD_SDK_ROOT}/host/usr/lib/llvm-18")
set(CMAKE_C_COMPILER "${_sela_host_llvm}/bin/clang" CACHE FILEPATH "Build-host Clang")
set(CMAKE_CXX_COMPILER "${_sela_host_llvm}/bin/clang++" CACHE FILEPATH "Build-host Clang++")
set(CMAKE_C_COMPILER_TARGET "${SELA_DEVICE_TARGET}-unknown-linux-gnu")
set(CMAKE_CXX_COMPILER_TARGET "${CMAKE_C_COMPILER_TARGET}")
set(CMAKE_LINKER "${_sela_host_llvm}/bin/ld.lld" CACHE FILEPATH "Build-host LLD")
set(CMAKE_AR "${_sela_host_llvm}/bin/llvm-ar" CACHE FILEPATH "Build-host archiver")
set(CMAKE_RANLIB "${_sela_host_llvm}/bin/llvm-ranlib" CACHE FILEPATH "Build-host ranlib")
set(_sela_gcc "--gcc-install-dir=${CMAKE_SYSROOT}/usr/lib/gcc/${_sela_triple}/13")
set(CMAKE_C_FLAGS_INIT "${_sela_gcc} -ffunction-sections -fdata-sections")
set(CMAKE_CXX_FLAGS_INIT "${_sela_gcc} -ffunction-sections -fdata-sections")
set(_sela_link "-fuse-ld=${CMAKE_LINKER} -Wl,--gc-sections -Wl,-rpath-link,${CMAKE_SYSROOT}/usr/lib/${_sela_multiarch}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_sela_link}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_sela_link}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_sela_link}")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}" "${SELA_SDK_ROOT}/host")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES SELA_SDK_ROOT SELA_DEVICE_TARGET SELA_BUILD_SDK_ROOT)
