# Cross-build a device ABI with the unmodified build-host Clang.
get_filename_component(_sela_repository "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(SELA_BUILD_SDK_ROOT "${_sela_repository}/.sdk" CACHE PATH "Pinned build-host SDK")
if(NOT SELA_SDK_ROOT OR NOT SELA_DEVICE_TARGET)
  message(FATAL_ERROR "Set SELA_SDK_ROOT and a registered SELA_DEVICE_TARGET")
endif()
find_program(_sela_python python3 REQUIRED NO_CMAKE_FIND_ROOT_PATH)
execute_process(COMMAND "${_sela_python}" "${_sela_repository}/sdk/targets.py" cmake "${SELA_DEVICE_TARGET}"
  OUTPUT_VARIABLE _sela_target_metadata RESULT_VARIABLE _sela_target_status)
if(NOT _sela_target_status EQUAL 0)
  message(FATAL_ERROR "Unknown device target: ${SELA_DEVICE_TARGET}")
endif()
# Target metadata is generated from the checked-in registry, not caller input.
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/sela-target.cmake" "${_sela_target_metadata}")
include("${CMAKE_CURRENT_BINARY_DIR}/sela-target.cmake")
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR "${SELA_DEVICE_TARGET}")
set(_sela_triple "${SELA_TARGET_SYSROOT_TRIPLE}")
set(_sela_multiarch "${SELA_TARGET_MULTIARCH}")
set(CMAKE_SYSROOT "${SELA_SDK_ROOT}/sysroots/${_sela_triple}")
set(_sela_host_llvm "${SELA_BUILD_SDK_ROOT}/host/usr/lib/llvm-18")
set(CMAKE_C_COMPILER "${_sela_host_llvm}/bin/clang" CACHE FILEPATH "Build-host Clang")
set(CMAKE_CXX_COMPILER "${_sela_host_llvm}/bin/clang++" CACHE FILEPATH "Build-host Clang++")
set(CMAKE_C_COMPILER_TARGET "${SELA_TARGET_TRIPLE}")
set(CMAKE_CXX_COMPILER_TARGET "${CMAKE_C_COMPILER_TARGET}")
set(CMAKE_LINKER "${_sela_host_llvm}/bin/ld.lld" CACHE FILEPATH "Build-host LLD")
set(CMAKE_AR "${_sela_host_llvm}/bin/llvm-ar" CACHE FILEPATH "Build-host archiver")
set(CMAKE_RANLIB "${_sela_host_llvm}/bin/llvm-ranlib" CACHE FILEPATH "Build-host ranlib")
set(_sela_gcc "--gcc-install-dir=${CMAKE_SYSROOT}/usr/lib/gcc/${SELA_TARGET_GCC_TRIPLE}/13")
string(JOIN " " _sela_target_flags ${SELA_TARGET_CLANG_ARGS})
set(CMAKE_C_FLAGS_INIT "${_sela_gcc} -ffunction-sections -fdata-sections ${_sela_target_flags}")
set(CMAKE_CXX_FLAGS_INIT "${_sela_gcc} -ffunction-sections -fdata-sections ${_sela_target_flags}")
set(_sela_link "-fuse-ld=${CMAKE_LINKER} -Wl,--gc-sections -Wl,-rpath-link,${CMAKE_SYSROOT}/usr/lib/${_sela_multiarch}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_sela_link}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_sela_link}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_sela_link}")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}" "${SELA_SDK_ROOT}/host")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES SELA_SDK_ROOT SELA_DEVICE_TARGET SELA_BUILD_SDK_ROOT)
