# Cross-build either native device ABI with the unmodified publisher Clang.
get_filename_component(_nier_repository "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(NIER_BUILD_SDK_ROOT "${_nier_repository}/.sdk" CACHE PATH "Pinned build-host SDK")
if(NOT NIER_SDK_ROOT OR NOT NIER_DEVICE_TARGET MATCHES "^(x86_64|i686)$")
  message(FATAL_ERROR "Set NIER_SDK_ROOT and NIER_DEVICE_TARGET=x86_64|i686")
endif()
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR "${NIER_DEVICE_TARGET}")
set(_nier_triple "${NIER_DEVICE_TARGET}-linux-gnu")
if(NIER_DEVICE_TARGET STREQUAL "i686")
  set(_nier_multiarch i386-linux-gnu)
else()
  set(_nier_multiarch x86_64-linux-gnu)
endif()
set(CMAKE_SYSROOT "${NIER_SDK_ROOT}/sysroots/${_nier_triple}")
set(_nier_host_llvm "${NIER_BUILD_SDK_ROOT}/host/usr/lib/llvm-18")
set(CMAKE_C_COMPILER "${_nier_host_llvm}/bin/clang" CACHE FILEPATH "Build-host Clang")
set(CMAKE_CXX_COMPILER "${_nier_host_llvm}/bin/clang++" CACHE FILEPATH "Build-host Clang++")
set(CMAKE_C_COMPILER_TARGET "${NIER_DEVICE_TARGET}-unknown-linux-gnu")
set(CMAKE_CXX_COMPILER_TARGET "${CMAKE_C_COMPILER_TARGET}")
set(CMAKE_LINKER "${_nier_host_llvm}/bin/ld.lld" CACHE FILEPATH "Build-host LLD")
set(CMAKE_AR "${_nier_host_llvm}/bin/llvm-ar" CACHE FILEPATH "Build-host archiver")
set(CMAKE_RANLIB "${_nier_host_llvm}/bin/llvm-ranlib" CACHE FILEPATH "Build-host ranlib")
set(_nier_gcc "--gcc-install-dir=${CMAKE_SYSROOT}/usr/lib/gcc/${_nier_triple}/13")
set(CMAKE_C_FLAGS_INIT "${_nier_gcc} -ffunction-sections -fdata-sections")
set(CMAKE_CXX_FLAGS_INIT "${_nier_gcc} -ffunction-sections -fdata-sections")
set(_nier_link "-fuse-ld=${CMAKE_LINKER} -Wl,--gc-sections -Wl,-rpath-link,${CMAKE_SYSROOT}/usr/lib/${_nier_multiarch}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_nier_link}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_nier_link}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_nier_link}")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}" "${NIER_SDK_ROOT}/host")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES NIER_SDK_ROOT NIER_DEVICE_TARGET NIER_BUILD_SDK_ROOT)
